Repository holochain/app-spec-rust, pull requests merged in 2018-10, with the labels that each got.

#18 README udpate to standard style
  LICENSE
  README.md
Labels: review

#17 Commit working
  .travis.yml
  build_and_test.sh
  docker/Dockerfile.app-spec-rust
  docker/ci
  docker/run-ci
  test/dist/bundle.js
  test/test.js
  zomes/blog/code/src/main_capability.rs
  zomes/blog/code/src/post_validations.rs
Labels: CI, review

#22 switch to hcdev test
  .gitignore
  .hcignore
  README.md
  build_and_test.sh
  docker/test
  test/dist/bundle.js
  test/package-lock.json
  test/test.js
Labels: review

#20 Get working
  .gitignore
  README.md
  build_and_test.sh
  docker/Dockerfile.app-spec-rust
  docker/ci
  docker/test
  docker/update
  test/dist/bundle.js
  test/package-lock.json
  test/package.json
  test/test.js
  zomes/blog/code/src/main_capability.rs
  zomes/blog/code/src/post_validations.rs
Labels: review

#29 Accommodate changes after HDK type refactoring.
  docker/update
  test/test.js
  zomes/blog/code/Cargo.toml
  zomes/blog/code/src/main_capability.rs
  zomes/blog/code/src/post_validations.rs
Labels: review

#31 updated .hcignore file for license and build script
  .hcignore
Labels: review

#32 Get with options
  zomes/blog/code/src/hc_lifecycle_capability.rs
  zomes/blog/code/src/main_capability.rs
  zomes/blog/code/src/post_validations.rs
Labels: review

#19 Validations for entries
  test/test.js
  zomes/blog/code/Cargo.toml
  zomes/blog/code/src/lib.rs
  zomes/blog/code/src/main_capability.rs
  zomes/blog/code/src/post.rs
  zomes/blog/code/src/post_validations.rs
Labels: devcamp, review

#33 Links round-trip & AGENT_KEY_HASH
  test/test.js
  zomes/blog/capabilities/main/manifest.json
  zomes/blog/code/src/main_capability.rs
Labels: review

#34 `define_zome!` macro awesomeness
  docker/update
  zomes/blog/capabilities/hc_lifecycle/manifest.json
  zomes/blog/code/src/blog.rs
  zomes/blog/code/src/hc_lifecycle_capability.rs
  zomes/blog/code/src/lib.rs
  zomes/blog/code/src/main_capability.rs
  zomes/blog/code/src/post.rs
Labels: review

#35 updates to for simplified get_entry()
  zomes/blog/code/src/blog.rs
  zomes/blog/code/src/post.rs
Labels: review

#28 Implement "hash_entry" (make_hash)
  test/test.js
  zomes/blog/capabilities/main/manifest.json
  zomes/blog/code/src/blog.rs
  zomes/blog/code/src/lib.rs
Labels: devcamp, review

#39 set version to 0.0.1 for developer preview release
  zomes/blog/code/Cargo.toml
Labels: review

#42 Remove zome JSON
  docker/update
  zomes/blog/capabilities/main/manifest.json
  zomes/blog/entry_types/post/manifest.json
Labels: review

#24 Call implemented
  test/package-lock.json
  test/test.js
  zomes/blog/code/src/blog.rs
  zomes/blog/code/src/lib.rs
  zomes/summer/code/.build
  zomes/summer/code/Cargo.toml
  zomes/summer/code/src/lib.rs
Labels: devcamp, review

#43 Hotfix for failing tests: was missing new readline dependency
  docker/Dockerfile.app-spec-rust
  docker/update
Labels: review
